Adding example.
Cogmasters/concord-docs pull request #2
Opened 2022-01-08 01:38 UTC by ThePedroo

2022-01-08 20:08 UTC, lcsmuller commented on docs/source/discord/resources/channel/methods/add_thread_member.rst
> +   // The channel that you executed the channel must be a thread.
```suggestion
   // channel_id must be from a thread channel
```

2022-01-08 20:11 UTC, lcsmuller commented on docs/source/discord/resources/channel/methods/create_channel_invite.rst
> +   discord_async_next(client, NULL);
```suggestion
```

2022-01-08 20:11 UTC, lcsmuller commented on docs/source/discord/resources/channel/methods/create_message.rst
> +   discord_async_next(client, NULL);
```suggestion
```

2022-01-08 20:12 UTC, lcsmuller commented on docs/source/discord/resources/channel/methods/crosspost_message.rst
> +
```suggestion
```

2022-01-08 20:12 UTC, lcsmuller commented on docs/source/discord/resources/channel/methods/delete_all_reactions.rst
> +   struct discord_channel ret;
```suggestion
```

2022-01-08 20:16 UTC, lcsmuller commented on docs/source/discord/resources/channel/methods/delete_all_reactions_for_emoji.rst
> +
```suggestion
```

2022-01-08 20:17 UTC, lcsmuller commented on docs/source/discord/resources/channel/methods/delete_channel_permission.rst
> +   u64_snowflake_t id = 1231231232131ULL;
```suggestion
   u64_snowflake_t id = 1231231232131ULL; // ficticious channel ID
```

2022-01-08 20:17 UTC, lcsmuller commented on docs/source/discord/resources/channel/methods/edit_channel_permissions.rst
> +   u64_snowflake_t id = 1231231232131ULL;
```suggestion
   u64_snowflake_t id = 1231231232131ULL; // ficticious channel ID
```

2022-01-08 20:22 UTC, lcsmuller commented on docs/source/discord/resources/channel/methods/edit_message.rst
> +   discord_edit_message(client, msg->channel_id, ret.id, &paramss, NULL);
```suggestion
   discord_create_message(client, 
                          msg->channel_id,
                          &(struct discord_create_message_params){ 
                            .content = "Hello there?" 
                          },
                          &ret);
   
   discord_edit_message(client,
                        msg->channel_id,
                        ret.id,
                        &(struct discord_edit_message_params){
                          .content = "Such a fast response!"
                        },
                        NULL);
```

2022-01-08 20:23 UTC, lcsmuller commented on docs/source/discord/resources/channel/methods/follow_news_channel.rst
> +   u64_snowflake_t id = 1231231232131ULL;
```suggestion
   u64_snowflake_t id = 1231231232131ULL; // ficticious channel ID
```

2022-01-08 20:24 UTC, lcsmuller commented on docs/source/discord/resources/channel/methods/get_channel.rst
> +   char text[128]
```suggestion
```

2022-01-08 20:24 UTC, lcsmuller commented on docs/source/discord/resources/channel/methods/get_channel.rst
> +
```suggestion
```

2022-01-08 20:25 UTC, lcsmuller commented on docs/source/discord/resources/channel/methods/get_channel.rst
> +   snprint(text, sizeof(text), "The name of this channel is: %s", ret.name)
```suggestion
   printf("The name of this channel is: %s", ret.name)
```

2022-01-08 20:27 UTC, lcsmuller commented on docs/source/discord/resources/channel/methods/unpin_message.rst
> +   u64_snowflake_t id = 1231231232131ULL;
```suggestion
   u64_snowflake_t id = 1231231232131ULL; // ficticious channel ID
```

2022-01-08 20:28 UTC, lcsmuller commented on docs/source/discord/resources/channel/methods/remove_thread_member.rst
> +   discord_remove_thread_member(client, msg->channel_id, msg->author.id);
```suggestion
   discord_remove_thread_member(client, msg->channel_id, msg->author->id);
```

2022-01-08 20:28 UTC, ThePedroo commented on docs/source/discord/resources/channel/methods/edit_message.rst
> +   discord_edit_message(client, msg->channel_id, ret.id, &paramss, NULL);
Changing some things.

2022-01-08 20:28 UTC, lcsmuller commented on docs/source/discord/resources/channel/methods/leave_thread.rst
> +   u64_snowflake_t id = 1231231232131ULL;
```suggestion
   u64_snowflake_t id = 1231231232131ULL; // ficticious channel ID
```

2022-01-08 20:28 UTC, lcsmuller commented on docs/source/discord/resources/channel/methods/join_thread.rst
> +   u64_snowflake_t id = 1231231232131ULL;
```suggestion
   u64_snowflake_t id = 1231231232131ULL; // ficticious channel ID
```

2022-01-08 20:29 UTC, lcsmuller commented on docs/source/discord/resources/channel/methods/get_reactions.rst
> +
```suggestion
```

2022-01-08 20:31 UTC, lcsmuller commented on docs/source/discord/resources/channel/methods/get_channel_message.rst
> +   discord_message_cleanup(rett);
```suggestion
   struct discord_message ret1;
   struct discord_message ret2;

   struct discord_create_message_params params = { .content = "Hey!" };

   discord_create_message(client, msg->channel_id, &params, &ret1);
   
   discord_get_channel_message(client, msg->channel_id, ret1.id, &ret2);
   
   printf("I said: %s", ret2.content);
   
   discord_message_cleanup(&ret1);
   discord_message_cleanup(&ret1);
```

2022-01-08 20:34 UTC, ThePedroo commented on docs/source/discord/resources/channel/methods/get_channel_message.rst
> +   discord_message_cleanup(rett);
Rename variable's name

2022-01-08 20:35 UTC, lcsmuller commented on docs/source/discord/resources/channel/methods/add_thread_member.rst
> +   discord_add_thread_member(client, msg->channel_id, msg->author.id);
```suggestion
   discord_add_thread_member(client, msg->channel_id, msg->author->id); 
```

2022-01-08 20:36 UTC, lcsmuller commented on docs/source/discord/resources/channel/methods/create_channel_invite.rst
> +   discord_create_message(client, msg -> channel_id, &params, NULL);
```suggestion
   discord_create_message(client, msg->channel_id, &params, NULL);
   
   discord_invite_cleanup(&ret);
```

2022-01-08 20:36 UTC, lcsmuller commented on docs/source/discord/resources/channel/methods/create_message.rst
> +   discord_create_message(client, msg -> channel_id, &params, NULL);
```suggestion
   struct discord_create_message_params params = { .content = "Pong!" };
   discord_create_message(client, msg->channel_id, &params, NULL);
```

2022-01-08 20:37 UTC, lcsmuller commented on docs/source/discord/resources/channel/methods/crosspost_message.rst
> +   discord_crosspost_message(client, msg->channel_id, msg->id, &ret);
```suggestion
   discord_crosspost_message(client, msg->channel_id, msg->id, &ret);
   
   discord_message_cleanup(&ret);
```

2022-01-08 20:39 UTC, lcsmuller commented on docs/source/discord/resources/channel/methods/delete_all_reactions.rst
> +   u64_snowflake_t message_id = strtoull(msg->content, NULL, 10);
```suggestion
   u64_snowflake_t message_id = strtoull(msg->content, NULL, 10); // assuming msg->content holds a message ID
```

2022-01-08 20:39 UTC, lcsmuller commented on docs/source/discord/resources/channel/methods/delete_channel.rst
> +   printf("Deleted channel %s", ret.name);
```suggestion
   printf("Deleted channel %s", ret.name);
   
   discord_channel_cleanup(&ret);
```

2022-01-08 20:41 UTC, lcsmuller commented on docs/source/discord/resources/channel/methods/edit_message.rst
> +                        NULL);
```suggestion
   discord_edit_message(client,
                        msg->channel_id,
                        ret.id,
                        &(struct discord_edit_message_params){
                          .content = "Such a fast response!"
                        },
                        NULL);
  
   discord_message_cleanup(&ret); 
```

2022-01-08 20:42 UTC, lcsmuller commented on docs/source/discord/resources/channel/methods/get_channel_messages.rst
> +       printf("%s\n", ret[i]->content);
```suggestion
   discord_get_channel_messages(client, msg->channel_id, NULL, &ret);
   
   if (ret)
     for (int i = 0; ret[i]; ++i)
       printf("%s\n", ret[i]->content);
  
   discord_message_list_free(ret);
```

2022-01-08 20:43 UTC, lcsmuller commented on docs/source/discord/resources/channel/methods/get_pinned_messages.rst
> +       printf("%s\n", ret[i]->content);
```suggestion
   discord_get_pinned_messages(client, msg->channel_id, &ret);
   
   if (ret)
     for (int i = 0; ret[i]; ++i)
       printf("%s\n", ret[i]->content);
       
   discord_message_list_free(ret);
```

2022-01-08 20:44 UTC, lcsmuller commented on docs/source/discord/resources/channel/methods/get_reactions.rst
> +       printf("%s\n", ret[i]->username);
```suggestion
   struct discord_user **ret;

   discord_create_reaction(client, msg->channel_id, msg->id, 0, "😄");
   
   discord_get_reactions(client, msg->channel_id, msg->id, 0, "😄", NULL, &ret);
   
   if (ret)
     for (int i = 0; ret[i]; ++i)
       printf("%s\n", ret[i]->username);
       
   discord_user_list_free(ret);
```

2022-01-08 20:44 UTC, lcsmuller commented on docs/source/discord/resources/channel/methods/pin_message.rst
> +   discord_pin_message(client, msg->channel_id, ret.id);
```suggestion
   discord_pin_message(client, msg->channel_id, ret.id);
   
   discord_message_cleanup(&ret);
```

2022-01-09 14:48 UTC, lcsmuller requested changes
Great job, just a tiny change that needs to be addressed first

2022-01-09 14:48 UTC, lcsmuller commented on docs/source/discord/resources/channel/methods/delete_user_reaction.rst
> +   discord_delete_user_reaction(client, msg->channel_id, msg->id, msg->id, 0, "😄");
Repeats msg->id for user_id

2022-01-09 16:38 UTC, ThePedroo commented on docs/source/discord/resources/channel/methods/delete_user_reaction.rst
> +   discord_delete_user_reaction(client, msg->channel_id, msg->id, msg->id, 0, "😄");
Done

2022-01-09 16:45 UTC, lcsmuller approved these changes

2022-01-09 16:46 UTC, merged